export const THEMES = {
  gold: {
    id: 'gold',
    name: 'Black & Gold',
    description: 'Classic & Elegant',
    bg: '#000000',
    card: '#111111',
    primary: '#C4A000',
    text: '#FFFFFF',
    subtext: '#666666',
    border: '#222222',
    emoji: '✨',
  },
  focus: {
    id: 'focus',
    name: 'Deep Focus',
    description: 'Calm & Concentrated',
    bg: '#080C18',
    card: '#0F1629',
    primary: '#00CFFF',
    text: '#E8F4FF',
    subtext: '#4A6A8A',
    border: '#1A2A40',
    emoji: '🧊',
  },
  energy: {
    id: 'energy',
    name: 'High Energy',
    description: 'Bold & Motivated',
    bg: '#0D0500',
    card: '#1A0D00',
    primary: '#FF6600',
    text: '#FFF5EE',
    subtext: '#8A6040',
    border: '#2A1500',
    emoji: '🔥',
  },
  creative: {
    id: 'creative',
    name: 'Creative Flow',
    description: 'Inspired & Expressive',
    bg: '#0A0515',
    card: '#150828',
    primary: '#BF5FFF',
    text: '#F5EEFF',
    subtext: '#7A5A9A',
    border: '#2A1545',
    emoji: '🎨',
  },
};

export const DEFAULT_THEME = 'gold';
